# Generated by Django 6.0.6 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Nome do produto'),
        ),
    ]
