# Generated by Django 6.0.6 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_sales_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="Extra"
            ),
        ),
    ]
