# Generated by Django 6.0.7 on 2026-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='category',
            field=models.CharField(choices=[('produto_fisico', 'Produto Físico'), ('produto_digital', 'Produto Digital'), ('assinatura', 'Assinatura'), ('servico', 'Serviço'), ('consultoria', 'Consultoria'), ('licenca', 'Licença'), ('comissao', 'Comissão'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='sales',
            name='external_ref',
            field=models.CharField(blank=True, help_text='ID da venda do sistema de origem ex 12867', max_length=100, null=True, verbose_name='Referência Externa'),
        ),
    ]
