# Generated by Django 6.0.6 on 2026-07-15 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Project name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "view_key",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="View Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("expired_at", models.DateTimeField(verbose_name="Expired at")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_project",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
