# Generated by Django 6.0.6 on 2026-07-15 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="project",
            name="expired_at",
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="id",
            ),
        ),
        migrations.CreateModel(
            name="ProjectAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("expired_at", models.DateTimeField(verbose_name="Expired at")),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project API Key",
                "verbose_name_plural": "Project API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
