# Generated by Django 6.0.6 on 2026-07-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_remove_project_api_key_remove_project_expired_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="projectapikey",
            name="api_key",
            field=models.CharField(
                default="",
                editable=False,
                max_length=100,
                unique=True,
                verbose_name="API Key",
            ),
        ),
    ]
