# Generated by Django 6.0.6 on 2026-07-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_is_active_alter_projectapikey_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="view_key",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="View Key"
            ),
        ),
    ]
