# Generated by Django 6.0.6 on 2026-07-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapikey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
