# Generated by Django 6.0.6 on 2026-07-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectapikey_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapikey',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='projects.project'),
        ),
    ]
