# Generated by Django 6.0.6 on 2026-07-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_collaborator_unique_collaborator_for_same_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Accepted'),
        ),
    ]
