# Generated by Django 6.0.7 on 2026-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_collaborator_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("ACCEPTED", "accepted"),
                    ("REJECTED", "rejected"),
                ],
                default="PENDING",
                verbose_name="Status",
            ),
        ),
    ]
