# Generated by Django 6.0.7 on 2026-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_collaborator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'administrator'), ('SECONDARY', 'secondary')], default='SECONDARY', verbose_name='Collaborator'),
        ),
    ]
