services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 5s

  django:
    build: .
    container_name: django
    command: >
      uvicorn core.asgi:application
      --host 0.0.0.0
      --port 8000
      --workers 2
      --loop uvloop
      --http httptools
      --log-level info
      --access-log
      --reload
    restart: unless-stopped
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      AMQP_URL: ${AMQP_URL}
    volumes:
      - .:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # 3. Main Celery Worker
  celery_worker:
    build: .
    command: celery -A core.celery_app worker --loglevel=info
    container_name: celery_worker
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # 4. Celery Beat (Periodic/Scheduled Tasks Scheduler)
  celery_beat:
    build: .
    command: celery -A core.celery_app beat --loglevel=info
    container_name: celery_beat
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # App connection port
      - "15672:15672" # Management UI port
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s # Give RabbitMQ time to fully boot up
    volumes:
      - rabbitmq_storage:/var/lib/rabbitmq

  flower:
    image: mher/flower
    container_name: flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH}
    ports:
      - "5555:5555"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5555/"]
      interval: 10s      
      timeout: 5s        
      retries: 3         
      start_period: 5s   
    env_file:
      - .env
    entrypoint: [] # Limpa o entrypoint original da imagem
    command: ["celery", "flower", "--broker=${CELERY_BROKER_URL}", "--port=5555", "--auto_refresh=True", "--auto_refresh_interval=3000"]
  
volumes:
  postgres_data:
  redis_data:
  rabbitmq_storage:
