# Generated by Django 6.0.7 on 2026-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('INVITATION', 'Invitation'), ('INFO', 'Info'), ('SALES', 'Sales'), ('EXPENSE', 'Expense'), ('REPORT', 'Report')], default='INFO', max_length=50, verbose_name='Type')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actionUrl', models.URLField(blank=True, verbose_name='Action URL')),
            ],
        ),
    ]
